language: python
python:
 - "3.5"
 - "3.8"

install:
 - sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev
 - pip install -r requirements.txt
 - pip install coveralls

script:
 - coverage run --source=django_webp manage.py test

after_success:
 - coveralls
