language: python
python:
 - "2.6" 
 - "2.7"
 - "3.3"

install:
 - pip install -r requirements.txt
 - pip install coveralls

script:
 - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms1-dev libwebp-dev
 - coverage run --source=django_webp manage.py test

after_success:
 - coveralls